### ISSUE TITLE
Part 1 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/Amanda_Blubaugh-project#1]
I don't see either a description of the data or a description of the planned analysis. Did I miss them?

**Comment by alblubaugh** [comment]
Did you open the word document "Main Project Document" link under overview?  I have an abstract title describing the overview and the source of the data I plan to use. 

If this is not enough, I can certainly add more information and plan to regardless, and can also add the information somewhere else instead of a word document if preferred.

I also added information about the project to my class project discussion thread on elc last Friday- I hope that helps!

**Comment by andreashandel** [comment]
I only see a list of data files in the Rmd file (don't see anything in the word document). Unfortunately based on that, I don't really know what your data contains. I assume it's sequences? Or something else? What variables are measured, how will you use that for analysis? I can't provide useful feedback at this stage without having more information about the data. But I assume you have thought about how to do the proposed analysis with that data, so go ahead with it, we'll hope it works out :).

**Comment by alblubaugh** [comment]
It is interesting you see the list of data files, as I tried to add the data files into a portion of my .Rmd word doc and when I pushed successfully to GitKrackin, I could not see the changes myself.  I still see just my abstract and a short intro on the data source. 

I am thinking it may be that I forgot to knit the .Rmd prior to saving and push? I am unsure but will make sure it is updated shortly. Have you ever had this issue?

**Comment by andreashandel** [comment]
I regularly forget to knit documents before pushing, but not sure what is going on in your case. But even in the Rmd file, the brief listing of the data wasn't enough for me to fully understand. I guess I"ll get a clearer idea once you submit part 2.
